apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ekl-k8s-istio-edit
rules:
  - apiGroups:
    - networking.istio.io
    resources:
      - virtualservices
      - gateways
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete